name: Build and Run Unit Test

on:
  push:

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: use Node.js 14.x
        uses: actions/setup-node@v4
        with:
          node-version: 14.x
      - name: install dependencies
        run: npm install
      # - name: test
      #   run: npm test
