name: Deploy main branch

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: use Node.js 14.x
        uses: actions/setup-node@v4
        with:
          node-version: 14.x
      - name: install dependencies
        run: npm install
      # - name: test
      #   run: npm test
      - name: serverless deploy
        uses: serverless/github-action@v3.2
        with:
          args: deploy --verbose --stage prod
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_ORG: ${{ secrets.OPENAI_ORG }}
